# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KEZC3HpxcGKoLjt0kDiZKNNk5FgAUGe
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile factorials.cpp
# #include <iostream>
# #include <omp.h>
# #include <cstdlib>  // for atoi
# using namespace std;
# 
# int serial_factorials(int number) {
#     double start_time = omp_get_wtime();
#     int factorial = 1;
#     for (int i = 1; i <= number; i++) {
#         factorial = factorial * i;
#     }
#     double end_time = omp_get_wtime();
#     cout << "Time : " << end_time - start_time << " seconds" << endl;
#     cout << "Your serial calculated factorial : " << factorial << endl;
#     return factorial;
# }
# 
# int parallel_factorials(int number) {
#     double start_time = omp_get_wtime();
#     int factorial = 1;
#     #pragma omp parallel for reduction(*:factorial)
#     for (int i = 1; i <= number; i++) {
#         factorial = factorial * i;
#     }
#     double end_time = omp_get_wtime();
#     cout << "Time : " << end_time - start_time << " seconds" << endl;
#     cout << "Your parallel calculated factorial : " << factorial << endl;
#     return factorial;
# }
# 
# int main(int argc, char* argv[]) {
#     if (argc < 2) {
#         cout << "Usage: ./factorials <number>" << endl;
#         return 1;
#     }
#     int number = atoi(argv[1]);
#     int serial_factorial = serial_factorials(number);
#     int parallel_factorial = parallel_factorials(number);
#     return 0;
# }
#

!g++ -fopenmp factorials.cpp -o factorials

!./factorials 10