# -*- coding: utf-8 -*-
"""07_Matrix_Multiplication_CUDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3Lf4ItUr0--C-FKfWkWtBk2ltCVg_aD
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile factorials.cpp
# #include <iostream>
# #include <omp.h>
# using namespace std;
# 
# int serial_factorials(int number) {
#     double start_time = omp_get_wtime();
#     int factorial = 1;
#     for (int i = 1; i <= number; i++) {
#         factorial = factorial * i;
#     }
#     double end_time = omp_get_wtime();
#     cout << "Time : " << end_time - start_time << " seconds" << endl;
#     cout << "Your serial calculated factorial : " << factorial << endl;
#     return factorial;
# }
# 
# int parallel_factorials(int number) {
#     double start_time = omp_get_wtime();
#     int factorial = 1;
#     #pragma omp parallel for reduction(*:factorial)
#     for (int i = 1; i <= number; i++) {
#         factorial *= i;
#     }
#     double end_time = omp_get_wtime();
#     cout << "Time : " << end_time - start_time << " seconds" << endl;
#     cout << "Your parallel calculated factorial : " << factorial << endl;
#     return factorial;
# }
# 
# int main() {
#     int number = 10;  // hardcoded value
#     int serial_factorial = 0, parallel_factorial = 0;
#     serial_factorial = serial_factorials(number);
#     parallel_factorial = parallel_factorials(number);
#     return 0;
# }
#

!g++ -fopenmp factorials.cpp -o factorials

!./factorials